apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-node-app
  labels:
    app: demo-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-node-app
  template:
    metadata:
      labels:
        app: demo-node-app
    spec:
      containers:
      - image: rick1113/demo-node-app:27
        name: demo-node-app
        ports:
        - containerPort: 3000
        env:
        - name: ENV_NAME
          valueFrom:
            configMapKeyRef:
              name: node-app-configmap
              key: env_name
---
apiVersion: v1
kind: Service
metadata:
  name: demo-node-app-service
spec:
  selector:
    app: demo-node-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000